[project]
name = "customer-success"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.5",
    "datalayer-pycrdt==0.12.17",
    "ipykernel>=7.1.0",
    "ipython>=9.8.0",
    "jupyter-collaboration==4.0.2",
    "jupyter-mcp-tools>=0.1.4",
    "jupyterlab==4.4.1",
    "langchain>=1.1.3",
    "langchain-aws>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.1.2",
    "langgraph>=1.0.4",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "sqlalchemy-redshift>=0.8.14",
]
